#!/usr/bin/env ruby
# frozen_string_literal: true

env = ENV.to_h

require "bundler/setup"
require "discourse_systray/systray"

# swap back env so we are not infected
ENV.replace(env)

# Parse command line arguments
if ARGV.include?("--debug")
  DiscourseSystray::Systray::OPTIONS[:debug] = true
end

# Run the systray
DiscourseSystray::Systray.new.run
